readonly true=1
readonly false=0


# VSCODE
INSTALL_VSCODE=true
# EXTENSIONS
INSTALL_GITLENS=true
INSTALL_DOCKER=true
INSTALL_REMOTE_SSH=false
INSTALL_ESLINT=true
INSTALL_PRETTIER=false
INSTALL_GIT_GRAPH=true
INSTALL_PROJECT_MANAGER=true
INSTALL_QUOKKA=true
INSTALL_VIM=true
INSTALL_ERROR_LENS=true

# Terminal
INSTALL_OHMYZSH=false
CUSTOMIZE_ZSH=true
INSTALL_NERDFONT=false
INSTALL_RIPGREP=false

# NVIM
INSTALL_NEOVIM=true
INSTALL_VIMPLUG=false
INSTALL_PACKER=true

# DOCKER
INSTALL_DOCKER=true
INSTALL_DOCKER_COMPOSE=true

# NODE
INSTALL_NODE=true
INSTALL_NVM=true

# OTHER
INSTALL_GIT=true
INSTALL_TMUX=true
INSTALL_VIRTUALBOX=true